### ISSUE TITLE
Rearrange descriptions and names so name comes first

### ISSUE THREAD

**Issue by darloth** [Alarcarr/Rising-Star#25]
In the localization files, I have put names after descriptions because I wrote the descs first and I usually never go into the loc files by hand.

Rearrange for consistency, easy enough.  Low priority for now but here's an issue to track it.

**Comment by DaloLorn** [comment]
*chuckles*

Me, I always write the localization by hand - it also helps maintain file integrity, instead of having half a dozen differently-named locale files for the same item type. (Notepad is more powerful than the SR2 locale editor due to a couple of bugs with special characters and the fact that I can make up locale keys without using them in a data file.)

**Comment by Alarcarr** [comment]
Afaik this is already done.Closing
